export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_REQUEST_SUCCESS = "ORDER_CREATE_REQUEST_SUCCESS";
export const ORDER_CREATE_REQUEST_ERROR = "ORDER_CREATE_REQUEST_ERROR";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_REQUEST_SUCCESS = "ORDER_DETAILS_REQUEST_SUCCESS";
export const ORDER_DETAILS_REQUEST_ERROR = "ORDER_DETAILS_REQUEST_ERROR";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_REQUEST_SUCCESS = "ORDER_PAY_REQUEST_SUCCESS";
export const ORDER_PAY_REQUEST_ERROR = "ORDER_PAY_REQUEST_ERROR";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_REQUEST_SUCCESS = "ORDER_LIST_REQUEST_SUCCESS";
export const ORDER_LIST_REQUEST_ERROR = "ORDER_LIST_REQUEST_ERROR";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";

export const ORDER_ALL_LIST_REQUEST = "ORDER_ALL_LIST_REQUEST";
export const ORDER_ALL_LIST_REQUEST_SUCCESS = "ORDER_ALL_LIST_REQUEST_SUCCESS";
export const ORDER_ALL_LIST_REQUEST_ERROR = "ORDER_ALL_LIST_REQUEST_ERROR";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_REQUEST_SUCCESS = "ORDER_DELIVER_REQUEST_SUCCESS";
export const ORDER_DELIVER_REQUEST_ERROR = "ORDER_DELIVER_REQUEST_ERROR";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";
