export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS";
export const USER_LOGIN_REQUEST_ERROR = "USER_LOGIN_REQUEST_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_REQUEST_SUCCESS = "USER_REGISTER_REQUEST_SUCCESS";
export const USER_REGISTER_REQUEST_ERROR = "USER_REGISTER_REQUEST_ERROR";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_REQUEST_SUCCESS = "USER_DETAILS_REQUEST_SUCCESS";
export const USER_DETAILS_REQUEST_ERROR = "USER_DETAILS_REQUEST_ERROR";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_REQUEST_SUCCESS =
  "USER_UPDATE_PROFILE_REQUEST_SUCCESS";
export const USER_UPDATE_PROFILE_REQUEST_ERROR =
  "USER_UPDATE_PROFILE_REQUEST_ERROR";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_REQUEST_SUCCESS = "USER_LIST_REQUEST_SUCCESS";
export const USER_LIST_REQUEST_ERROR = "USER_LIST_REQUEST_ERROR";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_REQUEST_SUCCESS = "USER_UPDATE_REQUEST_SUCCESS";
export const USER_UPDATE_REQUEST_ERROR = "USER_UPDATE_REQUEST_ERROR";
export const USER_UPDATE_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_REQUEST_SUCCESS = "USER_DELETE_REQUEST_SUCCESS";
export const USER_DELETE_REQUEST_ERROR = "USER_DELETE_REQUEST_ERROR";
